
-- Update Belrosa Master
UPDATE public.brands SET
  brand_brief = E'⚠️ CRITICAL PROJECT LOCK: This is ADANI REALTY''s BELROSA in AHMEDABAD, GUJARAT, INDIA. NEVER pull info from reference images. ONLY correct details: Adani Shantigram, Ahmedabad 382501 | 1800 108 0009 | adanirealty.com | 4 & 5 BHK Simplex, 5 & 6 BHK Duplex ONLY.\n\n## BRAND IDENTITY\nBelrosa by Adani Realty | Shantigram — "Your Kingdom in the Sky"\nLocation: Opp. Belvedere Golf & Country Club, Shantigram, Nr. Vaishnodevi Circle, SG Highway, Ahmedabad 382501 | Possession: May 2030\nUltra-luxury sky residences. 32 storeys, 125m, only 100 residences. 8 exclusive Duplexes up to 6,911 sq. ft.\nConfigs: 4 BHK Simplex 2,942 sq. ft. (A&B) | 5 BHK Simplex 3,664–5,092 sq. ft. (C&D) | 5 & 6 BHK Duplexes up to 6,911 sq. ft. | 3-level basement: 4–5 car parks per unit.\nSky Club: infinity pool, temp-controlled pool, kids pool, sky café, gym, spa, sauna & steam, home theatre, banquet hall, lounge café, reading nook, karaoke, billiards, pickleball.\nInside IGBC Gold Township: 600 acres, 50,000+ trees, 7-acre Musical Aqua Show lake, 1.5km Golf Promenade.\n\n## MUST-INCLUDE ELEMENTS\nAdani Realty | Shantigram logo: TOP-LEFT ONLY, ~5% inset\nRERA QR (RAA15538): TOP-RIGHT ONLY, slightly LOWER than Adani logo\nFull RERA: PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA15538/180725/310530\nBelrosa Lotus + wordmark: BOTTOM-RIGHT ONLY, stacked, copper/orange\nContact: 1800 108 0009 | Footer band: dark strip with address\nDisclaimer below footer. Label: *AI Generated / *Artistic Impression\n\n## MANDATORY PLACEMENT ZONES\nZONE 1 TOP-LEFT: Adani logo ONLY. ZONE 2 TOP-RIGHT: RERA QR ONLY (lower than logo). ZONE 3 CENTER-LEFT: Headlines left-aligned, upper-mid frame. ZONE 4 BOTTOM-RIGHT: Belrosa logo ONLY here — NEVER top, NEVER center, NEVER large. ZONE 5 BOTTOM STRIP: Dark footer + disclaimer.\nABSOLUTE RULE: NEVER 3 logos at top. Top has exactly 2 elements: Adani (left) + RERA QR (right).\n\n## VISUAL DIRECTION\nDefault: dark navy (#00334A) backgrounds or dark photography overlay — NEVER light/cream/white as primary bg. Warm golden-hour/dusk lighting. Wide-angle verticals for tower scale. Aerial for township. Lifestyle: aspirational but human. Navy overlay gradient on full-bleed photos, never pure black. Asymmetric editorial composition. Generous whitespace.\n\n## REFERENCE CREATIVE STRUCTURE\nTop 10-12%: Adani logo (left) + RERA QR (right, lower). Copy zone: left-aligned, 40-50% width, upper-half. Visual: full-bleed or right-dominant, warm dusk/golden-hour. Belrosa logo: bottom-right, small signature. Footer: 8-10% height, dark navy, full width.\n\n## EXAMPLE COPY\n"You don''t look at Belrosa. You look from it." | "Your Kingdom in the Sky." | "32 storeys. 125 metres. One address." | "Above the city. Below the sky." | "Shantigram is Ahmedabad''s Pride."\nCTAs: "Schedule a Private Visit." | "Explore Belrosa." | "Request a Viewing."',

  brand_voice_rules = E'Refined, specific, warm, assured, restrained, considered. HNIs (40–60), CXOs (38–55), established families. Secondary: NRIs, Adani investors.\n\nUse: "residences" (never flats/units), "private," "considered," "views," "elevated," "privileged," "kingdom," "Shantigram." Max 10–12 words per headline. Lead with feeling, follow with fact. Numerals for impact: "32 storeys," "125 metres."\n\nPillars: (1) Elevation — 125m, 32 floors, golf views. (2) Considered Privacy — 100 residences, private foyers, duplex layers. (3) Township Advantage — 600 acres, schools, hospital, golf club. (4) Duplex Distinction — 5 & 6 BHK, up to 6,911 sq. ft.\n\nDesired response: RECOGNISED (made for them), GROUNDED (Adani name, real facts), ELEVATED (quiet pull), CURIOUS (moved to visit). Never rushed or sold at.\n\nTypography: Adani corporate rounded sans-serif. Headlines bold all-caps. Supporting copy regular/light, tracked out. Italic for single-word emphasis. Never condensed/decorative.\n\nColour behaviour: Dark navy bg default. On navy: copper/white type. On light: navy type + copper accents. Navy #00334A + Orange #F58220 always default pair. Navy overlay gradient on photos, never pure black.',

  negative_prompts = E'⚠️ NEVER use data, addresses, phones, configs, or prices from reference images — ONLY use brand profile data.\nNEVER show 1/2/3 BHK — this project has ONLY 4 BHK, 5 BHK Simplex and 5 BHK, 6 BHK Duplex.\nNEVER show currency/price (₹, AED, "Starting from"). NEVER use phone other than 1800 108 0009. NEVER use website other than adanirealty.com.\nNEVER place Belrosa logo anywhere except BOTTOM-RIGHT. NEVER 3 logos at top — top has exactly Adani (left) + RERA QR (right).\nNEVER use light/cream/white as primary background — dark navy or dark photo overlay is default.\nNEVER use "luxury" standalone. NEVER generate generic taglines — only approved headlines from Example Copy.\nNEVER use urgency: "Hurry," "Act now," "Last chance." NEVER use superlatives: "World-class," "Iconic," "Timeless," "Most exclusive."\nNEVER use emojis, informal language, slang. NEVER pair navy with pure black #000000. NEVER use cold blue-toned/harsh flash imagery.\nNEVER omit RERA QR, Adani logo, or disclaimer. NEVER sacrifice whitespace.',

  updated_at = now()
WHERE id = '94703d77-e4d3-4934-b8d6-c952ff1bdb09';

-- Update Belrosa Exteriors
UPDATE public.brands SET
  brand_brief = E'⚠️ CRITICAL PROJECT LOCK: ADANI REALTY BELROSA, AHMEDABAD ONLY. NEVER pull info from reference images. Only: Shantigram, Ahmedabad 382501 | 1800 108 0009 | 4 & 5 BHK Simplex, 5 & 6 BHK Duplex ONLY.\n\n## BRAND IDENTITY\nBelrosa — Exteriors & Architecture profile. 32 storeys, 125m, Ahmedabad''s tallest residential tower. Only 100 residences. 8 exclusive Duplexes up to 6,911 sq. ft. Opp. Belvedere Golf & Country Club, inside 600-acre IGBC Gold Shantigram township.\n\n## MUST-INCLUDE ELEMENTS\nAdani Realty | Shantigram: TOP-LEFT ONLY. RERA QR (RAA15538): TOP-RIGHT ONLY, slightly lower. Belrosa Lotus + wordmark: BOTTOM-RIGHT ONLY — NEVER top, NEVER center. Footer: dark band with address. Disclaimer below.\nFull RERA: PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA15538/180725/310530\n\n## MANDATORY ZONES\nTop has exactly 2 elements: Adani (left) + RERA QR (right). NEVER 3 logos at top. Belrosa logo ONLY bottom-right.\n\n## VISUAL DIRECTION — EXTERIORS\nDark navy (#00334A) bg default — NEVER light/cream/white primary bg. Warm golden-hour/dusk lighting for tower facade. Wide-angle verticals emphasising 125m scale. Aerial/drone for township context — greenery, golf course, lake. Night tower facade shots sparingly for impact. Navy overlay gradient on full-bleed photos.\nBuilding must be accurate: proportions, materials, geometry unchanged. Vary only lighting (dawn/golden hour/dusk/night), angle (wide/aerial/street-level/close-up), atmosphere (clear/dramatic clouds/soft mist).\n\n## REFERENCE STRUCTURE\nTop 10-12%: logos. Copy: left-aligned, 40-50% width. Visual: right-dominant or full-bleed. Belrosa: bottom-right small. Footer: 8-10%, dark navy.\n\n## EXAMPLE COPY\n"32 storeys. 125 metres. One address." | "Above the city. Below the sky." | "Shantigram is Ahmedabad''s Pride."',

  brand_voice_rules = E'Refined, specific, warm, assured, restrained. Focus on tower scale (125m, 32 floors), commanding views, architectural presence. Use numerals for impact. Max 10–12 words per headline.\n\nPillars: (1) Elevation — 125m, unobstructed golf course views. (2) Township Scale — 600 acres, IGBC Gold, 50,000+ trees. (3) Architectural Statement — tallest in Shantigram, commanding skyline.\n\nTypography: Adani corporate rounded sans-serif. Bold all-caps headlines. Light/regular supporting copy. Colour: dark navy default bg. On navy: copper/white type. Navy #00334A + Orange #F58220 default pair.',

  negative_prompts = E'⚠️ NEVER use reference image data. ONLY 4/5 BHK Simplex + 5/6 BHK Duplex. NEVER show price/currency. Phone: 1800 108 0009 ONLY.\nNEVER place Belrosa logo except BOTTOM-RIGHT. NEVER 3 logos at top. NEVER light/cream/white primary bg.\nNEVER distort building proportions. NEVER use cold blue/harsh flash photography. NEVER squeeze/stretch architectural renders.\nNEVER use "luxury" standalone or generic taglines. NEVER urgency copy. NEVER superlatives. NEVER emojis. NEVER navy + pure black #000000. NEVER omit RERA/Adani logo/disclaimer.',

  updated_at = now()
WHERE id = 'b28cdce3-4dab-47c8-8c88-c747ac483325';

-- Update Belrosa Interiors
UPDATE public.brands SET
  brand_brief = E'⚠️ CRITICAL PROJECT LOCK: ADANI REALTY BELROSA, AHMEDABAD ONLY. NEVER pull info from reference images. Only: Shantigram, Ahmedabad 382501 | 1800 108 0009 | 4 & 5 BHK Simplex, 5 & 6 BHK Duplex ONLY.\n\n## BRAND IDENTITY\nBelrosa — Interiors profile. 4 BHK Simplex 2,942 sq. ft. | 5 BHK Simplex 3,664–5,092 sq. ft. | 5 & 6 BHK Duplexes up to 6,911 sq. ft. Private foyers, cantilevered viewing decks, abundant natural light, golf course and skyline views.\n\n## MUST-INCLUDE ELEMENTS\nAdani Realty | Shantigram: TOP-LEFT ONLY. RERA QR (RAA15538): TOP-RIGHT ONLY, slightly lower. Belrosa Lotus + wordmark: BOTTOM-RIGHT ONLY — NEVER top, NEVER center. Footer: dark band with address. Disclaimer below.\nFull RERA: PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA15538/180725/310530\n\n## MANDATORY ZONES\nTop has exactly 2 elements: Adani (left) + RERA QR (right). NEVER 3 logos at top. Belrosa logo ONLY bottom-right.\n\n## VISUAL DIRECTION — INTERIORS\nDark navy (#00334A) bg default — NEVER light/cream/white primary bg. Warm natural light interiors — golden-hour glow through large windows. Lifestyle: morning coffee on balcony, quiet moment on viewing deck — aspirational but human, never staged clichés.\nInterior shots: living rooms, bedrooms, private foyers, duplex staircases, viewing decks with golf course panorama. Warm amber tones, never cold/clinical.\n\n## REFERENCE STRUCTURE\nTop 10-12%: logos. Copy: left-aligned, 40-50% width. Visual: right-dominant or full-bleed. Belrosa: bottom-right small. Footer: 8-10%, dark navy.\n\n## EXAMPLE COPY\n"Every residence, a private foyer. Every morning, a golf course view." | "Your Kingdom in the Sky." | "Wake up to the golf course. Every morning."',

  brand_voice_rules = E'Refined, warm, considered. Focus on living experience — space, light, privacy, views. Use specific sizes (2,942 sq. ft., 6,911 sq. ft.) for impact. Max 10–12 words per headline.\n\nPillars: (1) Considered Privacy — private foyers, duplex layers, only 100 residences. (2) Living Experience — natural light, golf views, premium finishes. (3) Duplex Distinction — up to 6,911 sq. ft. across two private floors.\n\nTypography: Adani corporate rounded sans-serif. Bold all-caps headlines. Colour: dark navy default bg. Navy #00334A + Orange #F58220 default pair.',

  negative_prompts = E'⚠️ NEVER use reference image data. ONLY 4/5 BHK Simplex + 5/6 BHK Duplex. NEVER show price/currency. Phone: 1800 108 0009 ONLY.\nNEVER place Belrosa logo except BOTTOM-RIGHT. NEVER 3 logos at top. NEVER light/cream/white primary bg.\nNEVER use cold/clinical interior photography. NEVER use staged luxury-couple stock imagery.\nNEVER use "luxury" standalone or generic taglines. NEVER urgency copy. NEVER superlatives. NEVER emojis. NEVER navy + pure black #000000. NEVER omit RERA/Adani logo/disclaimer.',

  updated_at = now()
WHERE id = '80de8003-5a9c-4fd9-b6c7-6d671dfc48f2';

-- Update Belrosa Amenities
UPDATE public.brands SET
  brand_brief = E'⚠️ CRITICAL PROJECT LOCK: ADANI REALTY BELROSA, AHMEDABAD ONLY. NEVER pull info from reference images. Only: Shantigram, Ahmedabad 382501 | 1800 108 0009 | 4 & 5 BHK Simplex, 5 & 6 BHK Duplex ONLY.\n\n## BRAND IDENTITY\nBelrosa — Amenities profile. Sky Club at the crown: infinity pool, temperature-controlled pool, kids'' pool, sky café, gym, spa, sauna & steam, home theatre, banquet hall, lounge café, reading nook, karaoke, billiards, pickleball.\nTownship: 600 acres, 50,000+ trees, 7-acre Musical Aqua Show lake, 1.5km Golf Promenade, Belvedere Golf & Country Club, schools, hospital.\n\n## MUST-INCLUDE ELEMENTS\nAdani Realty | Shantigram: TOP-LEFT ONLY. RERA QR (RAA15538): TOP-RIGHT ONLY, slightly lower. Belrosa Lotus + wordmark: BOTTOM-RIGHT ONLY — NEVER top, NEVER center. Footer: dark band with address. Disclaimer below.\nFull RERA: PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA15538/180725/310530\n\n## MANDATORY ZONES\nTop has exactly 2 elements: Adani (left) + RERA QR (right). NEVER 3 logos at top. Belrosa logo ONLY bottom-right.\n\n## VISUAL DIRECTION — AMENITIES\nDark navy (#00334A) bg default — NEVER light/cream/white primary bg. Warm golden-hour light on amenity spaces. Sky Club shots: infinity pool at dusk with city panorama, sky café, gym with views. Township: aerial of 600-acre greenery, golf promenade, Musical Aqua Show lake.\nLifestyle: serene, aspirational — a quiet lap in the infinity pool, morning at the sky café. Never crowded or staged.\n\n## REFERENCE STRUCTURE\nTop 10-12%: logos. Copy: left-aligned, 40-50% width. Visual: right-dominant or full-bleed. Belrosa: bottom-right small. Footer: 8-10%, dark navy.\n\n## EXAMPLE COPY\n"The Sky Club. Where your mornings begin." | "A 600-acre world. Built for the life you''ve earned." | "Above the city. Below the sky."',

  brand_voice_rules = E'Refined, warm, experiential. Focus on lifestyle and amenity experience — Sky Club, township scale, community. Max 10–12 words per headline.\n\nPillars: (1) Sky Club — infinity pool, spa, gym, home theatre at the crown. (2) Township Advantage — 600 acres, golf club, Musical Aqua Show, schools, hospital. (3) Community — exclusive 100-residence community among like-minded residents.\n\nTypography: Adani corporate rounded sans-serif. Bold all-caps headlines. Colour: dark navy default bg. Navy #00334A + Orange #F58220 default pair.',

  negative_prompts = E'⚠️ NEVER use reference image data. ONLY 4/5 BHK Simplex + 5/6 BHK Duplex. NEVER show price/currency. Phone: 1800 108 0009 ONLY.\nNEVER place Belrosa logo except BOTTOM-RIGHT. NEVER 3 logos at top. NEVER light/cream/white primary bg.\nNEVER show crowded/staged amenity shots. NEVER use cold/clinical photography.\nNEVER use "luxury" standalone or generic taglines. NEVER urgency copy. NEVER superlatives. NEVER emojis. NEVER navy + pure black #000000. NEVER omit RERA/Adani logo/disclaimer.',

  updated_at = now()
WHERE id = 'd5d34b2e-f00f-49ec-9b29-91814a260171';
