
UPDATE public.brands
SET
  brand_brief = E'## BRAND IDENTITY\nBelrosa by Adani Realty | Shantigram — "Your Kingdom in the Sky"\nLocation: Opp. Belvedere Golf & Country Club, Shantigram, Nr. Vaishnodevi Circle, SG Highway, Ahmedabad 382501\nPossession: May 2030\n\nUltra-luxury sky residences — 4 BHK & 5 BHK Simplexes; 5 BHK & 6 BHK Duplexes. 32 storeys, 125m, only 100 residences. 8 exclusive Duplexes up to 6,911 sq. ft. with private foyers and cantilevered viewing decks.\n\nConfigurations: 4 BHK Simplex 2,942 sq. ft. (A & B) | 5 BHK Simplex 3,664–5,092 sq. ft. (C & D) | 5 & 6 BHK Duplexes up to 6,911 sq. ft. | 3-level basement: 4–5 car parks per unit.\n\nSky Club: infinity pool, temperature-controlled pool, kids'' pool, sky café, gym, spa, sauna & steam, home theatre, banquet hall, lounge café, reading nook, karaoke, billiards, pickleball.\n\nInside IGBC Gold-rated Township: 600 acres, 50,000+ trees, 7-acre Musical Aqua Show lake, 1.5km Golf Promenade, Belvedere Golf & Country Club.\n\n## MUST-INCLUDE ELEMENTS\nAdani Realty | Shantigram logo: TOP-LEFT, ~5% inset, generous clear space\nRERA QR (RAA15538): TOP-RIGHT, slightly LOWER than Adani logo — never parallel\nFull RERA: PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA15538/180725/310530\nBelrosa Lotus + BELROSA wordmark: BOTTOM-RIGHT, stacked, copper/orange\nContact: 1800 108 0009\nFooter band: dark strip with address text\nDisclaimer (small type below footer): "This is not a RERA advertisement or offer. Images are artistic impressions for reference only."\nLabel: *AI Generated / *Artistic Impression near relevant visual\n\n## VISUAL DIRECTION\nWarm golden-hour or dusk lighting default. Wide-angle verticals for tower scale. Aerial for township context. Lifestyle: aspirational but human — morning coffee on balcony, quiet deck moment. Night tower shots sparingly for impact. Navy overlay gradient on full-bleed photos, never pure black.\n\nLayout: left-aligned copy zone upper-to-mid frame. Hierarchy: headline → feature → support → CTA. Generous whitespace. Asymmetric editorial composition. Copper/gold linework and lotus motif as accents only.\n\n## EXAMPLE COPY\nHeadlines: "You don''t look at Belrosa. You look from it." | "Your Kingdom in the Sky." | "32 storeys. 125 metres. One address." | "Above the city. Below the sky."\nSubtext: "Only 100 residences. Across 32 floors." | "8 exclusive Duplexes. Up to 6,911 sq. ft." | "A 600-acre world. Built for the life you''ve earned."\nCTAs: "Schedule a Private Visit." | "Explore Belrosa." | "Request a Viewing."',

  brand_voice_rules = E'Refined, specific, warm, assured, restrained, considered. Speaks to HNIs (40–60), CXOs (38–55), established families with generational wealth. Secondary: NRIs from Ahmedabad, Adani Realty investors.\n\nUse: "residences" (never flats/units), "private," "considered," "views," "elevated," "privileged," "kingdom," "Shantigram." Short sentences — max 10–12 words per headline. Lead with feeling, follow with fact: "Wake up to the golf course. Every morning." Write numbers as numerals for impact.\n\nPillars: (1) Elevation — 125m, 32 floors, golf views, life above the ordinary. (2) Considered Privacy — only 100 residences, private foyers, duplex layers. (3) Township Advantage — 600 acres, schools, hospital, golf club, Musical Aqua Show. (4) Duplex Distinction — 5 & 6 BHK, up to 6,911 sq. ft., two private floors.\n\nDesired response: RECOGNISED (made for them), GROUNDED (Adani name, real facts), ELEVATED (quiet pull), CURIOUS (moved to visit). Never rushed, talked down to, or sold at.',

  negative_prompts = E'NEVER mention price, cost, crore, budget, affordable, value, cheap, competitive, ticket size. NEVER use urgency: "Hurry," "Act now," "Last chance," "Limited time," "Booking open." NEVER use hollow superlatives: "World-class," "Most exclusive," "Unmatched," "Best in class," "Spectacular," "Amazing," "Incredible," "Mind-blowing." NEVER use emojis. NEVER use "luxury" as standalone claim. NEVER use informal language, slang, "you guys," "folks." NEVER pair navy with pure black #000000. NEVER merge Belrosa and Adani logos into one unit. NEVER place logos on busy backgrounds without clear zone. NEVER use neon colours, sale-style treatments, heavy drop shadows, emboss, 3D text. NEVER use condensed/decorative typefaces. NEVER use stock imagery or blurry/pixelated images. NEVER use cold blue-toned or harsh flash photography. NEVER sacrifice whitespace. NEVER change layout structure when varying imagery.',

  updated_at = now()
WHERE id = '94703d77-e4d3-4934-b8d6-c952ff1bdb09';
